[tool.poetry]
name = "h1st"
version = "0.1.14.dev1"
description = "Human-First AI (H1st)"
authors = ["Aitomatic, Inc. <engineering@aitomatic.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://h1st.ai"
repository = "https://github.com/h1st-ai/h1st"
include = ["h1st/*"]


[tool.poetry.dependencies]
python = ">= 3.8, < 3.12"

# Data Processing
numpy = ">= 1.22.4"   # let higher dependencies figure
pandas = ">= 1.5.2"
pyarrow = ">= 10.0.1"
pyspark = ">= 3.3.1"

# Machine Learning / Deep Learning
imbalanced-learn = ">= 0.10.1"
scikit-fuzzy = ">= 0.4.2"
scikit-learn = ">= 1.2.0"
tensorflow = ">= 2.11.0"

# Trustworthy AI
graphviz = ">= 0.20.1"
lime = ">= 0.2.0.1"
shap = ">= 0.41.0"

# File Systems
fsspec = ">= 2022.11.0"
s3fs = ">= 2022.11.0"

# misc/other
click = ">= 8.0.4"   # let higher dependencies figure
python-dotenv = ">= 0.21.0"
pyyaml = ">= 6.0"
"ruamel.yaml" = ">= 0.17.21"
tqdm = ">= 4.64.1"
ulid-py = ">= 1.1.0"


[tool.poetry.dev-dependencies]
commitizen = ">= 2.39.1"
pre-commit = ">= 2.21.0"
pylint = ">= 2.15.10"
pytest = ">= 7.2.0"
sphinx = ">= 6.1.3"
sphinx-rtd-theme = ">= 1.1.1"


[tool.poetry.scripts]
h1st = 'h1st.utils.tools:h1st_cli'


[build-system]
requires = [
  "poetry-core >= 1.4.0",
]
build-backend = "poetry.core.masonry.api"


[tool.pylint.format]
max-line-length = 120
