[tool.poetry]
name = 'h1st'
version = '0.1.14.dev0'
description = 'Human-First AI (H1st)'
authors = ['Aitomatic, Inc. <engineering@aitomatic.com>']
license = 'Apache-2.0'
readme = 'README.md'
homepage = 'https://h1st.ai'
repository = 'https://github.com/h1st-ai/h1st'
include = ['h1st/*']


[tool.poetry.dependencies]
Python = '>= 3.8, < 3.11'

# Data Processing
NumPy = '>= 1.22.4'   # let higher dependencies figure
Pandas = '>= 1.5.0'
PyArrow = '>= 9.0.0'
PySpark = '>= 3.3.0'

# Machine Learning / Deep Learning
Imbalanced-Learn = '>= 0.9.1'
SciKit-Fuzzy = '>= 0.4.2'
SciKit-Learn = '>= 1.1.2'
TensorFlow = '>= 2.10.0'

# Trustworthy AI
GraphViz = '>= 0.20.1'
LIME = '>= 0.2.0.1'
SHAP = '>= 0.41.0'

# File Systems
FSSpec = '>= 2022.8.2'
S3FS = '>= 2022.8.2'

# misc/other
CLICK = '>= 8.0.4'   # let higher dependencies figure
Python-DotEnv = '>= 0.21.0'
PyYAML = '>= 6.0'
'Ruamel.YAML' = '>= 0.17.21'
Tqdm = '>= 4.64.1'
ULID-Py = '>= 1.1.0'


[tool.poetry.dev-dependencies]
Commitizen = '>= 2.35.0'
Pre-Commit = '>= 2.20.0'
PyLint = '>= 2.15.3'
PyTest = '>= 7.1.3'
Sphinx = '>= 5.2.3'
Sphinx-RtD-Theme = '>= 1.0.0'


[tool.poetry.scripts]
h1st = 'h1st.utils.tools:h1st_cli'


[build-system]
requires = [
  'Poetry-Core >= 1.3.1',
]
build-backend = 'poetry.core.masonry.api'


[tool.pylint.format]
max-line-length = 120
